language: ko-KR
tone_instructions: "변경의 문제점/한계를 구체적으로 지적하고, 비권장 이유를 근거와 함께 간결히 설명하세요. 대안은 선택지와 장단점을 병기하세요. 지적보다는 개선 방향에 집중하되, 학습 관점에서 논리 흐름이 분명하도록 작성하세요."

early_access: false             # 베타 기능 미사용
reviews:
  profile: assertive             # 단도직입적
  request_changes_workflow: false # change 요청 시 워크플로우 비활성화
  high_level_summary: true      # 요약 제공
  poem: false                   # 시 형식 비활성화
  review_status: false          # PR 상태코멘트 미표시
  collapse_walkthrough: false   # 상세 설명 접지 않음
  auto_review:
    enabled: true               # PR 자동 리뷰 활성화
    auto_incremental_review: true
    base_branches: ["be/dev", "fe/dev"]

chat:
  auto_reply: true              # PR 코멘트에 자동 답변
