version: 0.2

env:
  variables:
    SNS_TOPIC_ARN : "arn:aws:sns:ap-northeast-2:843255971531:coffee-shout"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - ls -la
      - chmod +x backend/gradlew

  build:
    commands:
      - cd backend && ./gradlew build
      - ls -la build/libs/
      - JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
      - echo "Found JAR file:" $JAR_FILE
      - cp "$JAR_FILE" ../coffee-shout-backend.jar

      # 스크립트 복사
      - cp -r ./scripts ../scripts/
      - chmod +x ../scripts/*.sh

      # appspec 복사
      - cp appspec.yml ../appspec.yml
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
          echo "Build failed, sending SNS notification..."
        
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "🚨 Build Failed: $CODEBUILD_INITIATOR" \
            --message "Build $CODEBUILD_BUILD_ID failed at $(date)" \
            --region "$AWS_DEFAULT_REGION"
        fi

artifacts:
  files:
    - coffee-shout-backend.jar
    - scripts/*
    - appspec.yml

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - 'backend/.gradle/**/*'