version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - cd backend
      - chmod +x gradlew

  build:
    commands:
      - cd backend
      - ./gradlew clean build
      - cp build/libs/*.jar ../coffee-shout-backend.jar

artifacts:
  files:
    - coffee-shout-backend.jar
