version: 0.2

env:
  variables:
    SNS_TOPIC_ARN: "arn:aws:sns:ap-northeast-2:843255971531:coffee-shout"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - cd backend
      - ls -la
      - chmod +x ./gradlew
      - docker info

  pre_build:
    commands:
      - sed 's/\${/$/g; s/}//g' src/main/resources/application.yml > /tmp/application-tmp.yml
      - envsubst < /tmp/application-tmp.yml > /tmp/application.yml
      - cat /tmp/application.yml
      - cp /tmp/application.yml src/main/resources/application.yml

      - sed 's/\${/$/g; s/}//g' src/main/resources/application-prod.yml > /tmp/application-prod-tmp.yml
      - envsubst < /tmp/application-prod-tmp.yml > /tmp/application-prod.yml
      - cat /tmp/application-prod.yml
      - cp /tmp/application-prod.yml src/main/resources/application-prod.yml

  build:
    commands:
      # prod 환경에서는 모든 테스트 실행
      - cat src/main/resources/application.yml
      - cat src/main/resources/application-prod.yml
      - ls src/test/resources
      - cat src/test/resources/application-test.yml
      - ./gradlew clean test -Dspring.profiles.active=test
      - ./gradlew build -x test
      - ls -la build/libs/
      - JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
      - echo "Found JAR file:" $JAR_FILE
      - cp "$JAR_FILE" ../coffee-shout-backend.jar

      # 스크립트 복사
      - cp -r ./scripts ../scripts/
      - chmod +x ../scripts/*.sh

      # appspec 복사
      - cp appspec-prod.yml ../appspec.yml
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
          echo "Build failed, sending SNS notification..."
        
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "🚨 Prod Build Failed: $CODEBUILD_INITIATOR" \
            --message "Prod Build $CODEBUILD_BUILD_ID failed at $(date)" \
            --region "$AWS_DEFAULT_REGION"
        fi

artifacts:
  files:
    - coffee-shout-backend.jar
    - scripts/*
    - appspec.yml

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'
