version: 0.2

env:
  variables:
    SNS_TOPIC_ARN: "arn:aws:sns:ap-northeast-2:843255971531:coffee-shout"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - cd backend
      - ls -la
      - chmod +x ./gradlew
      - docker info

  pre_build:
    commands:
      # 원본 설정 파일 백업
      - cp src/main/resources/application.yml /tmp/application-original.yml
      - cp src/main/resources/application-prod.yml /tmp/application-prod-original.yml
      
      # 테스트 먼저 실행 (원본 설정으로)
      - echo "Running tests with H2 configuration..."
      - ./gradlew clean test -Dspring.profiles.active=test --stacktrace
      
      # 테스트 성공 후 prod 설정 준비
      - echo "Preparing production configurations..."
      - sed 's/\${/$/g; s/}//g' /tmp/application-original.yml > /tmp/application-tmp.yml
      - envsubst < /tmp/application-tmp.yml > /tmp/application.yml
      - cat /tmp/application.yml

      - sed 's/\${/$/g; s/}//g' /tmp/application-prod-original.yml > /tmp/application-prod-tmp.yml
      - envsubst < /tmp/application-prod-tmp.yml > /tmp/application-prod.yml
      - cat /tmp/application-prod.yml

  build:
    commands:
      # prod 설정으로 교체
      - cp /tmp/application.yml src/main/resources/application.yml
      - cp /tmp/application-prod.yml src/main/resources/application-prod.yml
      
      # prod 빌드 (테스트 제외)
      - echo "Building with production profile..."
      - ./gradlew build -x test
      - ls -la build/libs/
      - JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
      - echo "Found JAR file:" $JAR_FILE
      - cp "$JAR_FILE" ../coffee-shout-backend.jar

      # 스크립트 복사
      - cp -r ./scripts ../scripts/
      - chmod +x ../scripts/*.sh

      # appspec 복사
      - cp appspec-prod.yml ../appspec.yml
      
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
          echo "Build failed, sending SNS notification..."
        
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "🚨 Prod Build Failed: $CODEBUILD_INITIATOR" \
            --message "Prod Build $CODEBUILD_BUILD_ID failed at $(date)" \
            --region "$AWS_DEFAULT_REGION"
        fi

artifacts:
  files:
    - coffee-shout-backend.jar
    - scripts/*
    - appspec.yml

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '.gradle/**/*'
