version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - ls -la
      - chmod +x backend/gradlew

  build:
    commands:
      - cd backend && ./gradlew clean build
      - ls -la backend/build/libs/
      - JAR_FILE=$(find backend/build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
      - echo "Found JAR file:" $JAR_FILE
      - cp "$JAR_FILE" coffee-shout-backend.jar

artifacts:
  files:
    - coffee-shout-backend.jar

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - 'backend/.gradle/**/*'