version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - ls -la
      - chmod +x backend/gradlew

  build:
    commands:
      - cd backend && ./gradlew clean build
      - cp backend/build/libs/*.jar coffee-shout-backend.jar

artifacts:
  files:
    - coffee-shout-backend.jar
