version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - ls -la
      - chmod +x backend/gradlew

  build:
    commands:
      - cd backend && ./gradlew clean build
      - ls -la build/libs/
      - JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
      - echo "Found JAR file:" $JAR_FILE
      - cp "$JAR_FILE" ../coffee-shout-backend.jar

      ## 도커 파일 복사
      - cp compose.yaml ../compose.yaml

      # 스크립트 복사
      - cp -r ./scripts ../scripts/
      - chmod +x ../scripts/*.sh

      # appspec 복사
      - cp appspec.yml ../appspec.yml


artifacts:
  files:
    - coffee-shout-backend.jar
    - scripts/*
    - appspec.yml
    - compose.yaml

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - 'backend/.gradle/**/*'