spring:
  application:
    name:
      coffee-shout
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}

room:
  removalDelay: 1h
  qr:
    width: 150
    height: 150
    presignedUrl:
      expirationHours: 1

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    enable:
      tomcat: true

  prometheus:
    metrics:
      export:
        enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true

websocket:
  docs:
    enabled: true
    base-package: "coffeeshout"
    app-path: "/app"
    topic-path: "/topic"
    server-url: "http://localhost:8080/ws"
    info:
      title: "커피빵 WebSocket API 명세서"
      version: "1.0.0"
      description: "실시간 웹소켓 통신 API 문서"

menu-category:
  default-image: "default image"
