spring:
  application:
    name:
      coffee-shout

logging:
  level:
    root: info

management:
  metrics:
    export:
      cloudwatch:
        enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

