spring:
  application:
    name:
      coffee-shout

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    enable:
      tomcat: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
      maximum-expected-value:
        http.server.requests: 2s # 예상 최대 응답 시간

  prometheus:
    metrics:
      export:
        enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true
