spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_shout
    username: root
    password: coffee-shout_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      s3:
        enabled: false
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_and_stop
  data:
    redis:
      host: localhost
      ssl:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,tracing"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        enabled: true
  metrics:
    enable:
      tomcat: true

room:
  qr:
    prefix: http://localhost:8080/join/

logging:
  level:
    coffeeshout: DEBUG
    org.springframework.web: INFO
