spring:
  application:
    name:
      coffee-shout
  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST:localhost}
      ssl:
        enabled: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

room:
  removalDelay: 1h
  qr:
    width: 150
    height: 150
    presignedUrl:
      expirationHours: 1
    s3-key-prefix: ${S3_QR_KEY_PREFIX}

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    enable:
      tomcat: true

  prometheus:
    metrics:
      export:
        enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true

websocket:
  docs:
    enabled: true
    base-package: "coffeeshout"
    app-path: "/app"
    topic-path: "/topic"
    server-url: "http://localhost:8080/ws"
    info:
      title: "커피빵 WebSocket API 명세서"
      version: "1.0.0"
      description: "실시간 웹소켓 통신 API 문서"

menu-category:
  default-image: "https://techcourse-project-2025.s3.ap-northeast-2.amazonaws.com/coffee-shout/images/default-category.svg"
