spring:
  application:
    name:
      coffee-shout

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
