spring:
  application:
    name:
      coffee-shout

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    enable:
      tomcat: true
  prometheus:
    metrics:
      export:
        enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true

room:
  cleanup:
    interval: 3600000 # 1 hour in milliseconds
