spring:
  cloud:
    aws:
      s3:
        enabled: false
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  data:
    redis:
      ssl:
        enabled: false

room:
  qr:
    prefix: http://localhost:8080/join/

logging:
  level:
    coffeeshout: DEBUG
    org.springframework.web: INFO
