spring:
  cloud:
    aws:
      s3:
        enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false

room:
  qr:
    prefix: http://localhost:8080/join/

logging:
  level:
    coffeeshout: DEBUG
    org.springframework.web: INFO
