spring:
  cloud:
    aws:
      s3:
        enabled: false
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_and_stop
  data:
    redis:
      host: localhost
      ssl:
        enabled: false

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318

tracing:
  sampling:
    probability: 1.0

room:
  qr:
    prefix: http://localhost:8080/join/

logging:
  level:
    coffeeshout: DEBUG
    org.springframework.web: INFO
