name: "Deploy Storybook to Chromatic"

on:
  pull_request:
    branches:
      - fe/dev
    types: [opened, synchronize]
    paths:
      - "frontend/**/*.stories.*"
      - "frontend/.storybook/**"

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend
          branchName: preview
          exitZeroOnChanges: true

      - name: Comment PR with Storybook URL
        uses: actions/github-script@v7
        if: github.event.action == 'opened'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📚 Storybook Preview\n\n🔗 **고정 URL**: https://preview--68db92900b71dbe8fcff669b.chromatic.com\n\n최신 스토리북이 배포되었습니다!`
            })
