name: "Deploy Storybook to Chromatic"

on:
  pull_request:
    branches:
      - fe/dev
    types: [opened, synchronize]
    paths:
      - "frontend/**/*.stories.*"
      - "frontend/.storybook/**"
      - "frontend/src/**"

env:
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: $CHROMATIC_PROJECT_TOKEN
          branchName: preview
          exitZeroOnChanges: true
