name: Frontend CD

on:
  pull_request:
    types: [closed] # PR이 닫힐 때만 실행
    branches:
      - fe/prod
    paths:
      - "frontend/**" # frontend 변경사항만

env:
  FE_PROD_PATH: fe-prod
  FE_CACHE_PATH: /*

jobs:
  ci:
    # PR이 실제로 merge되었을 때만 CI 실행
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/frontend-ci.yml

  cd:
    needs: ci
    # PR이 merge되었고 CI가 성공했을 때만 실행
    if: github.event.pull_request.merged == true && needs.ci.result == 'success'
    runs-on: [self-hosted, Linux, ARM64]

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Remove previous version app
        working-directory: .
        run: rm -rf frontend/

      - name: Download the built file from CI
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend
        timeout-minutes: 5

      - name: Upload to S3
        run: |
          aws s3 sync frontend s3://techcourse-project-2025/coffee-shout/${{ env.FE_PROD_PATH }}/ --delete

      - name: CloudFront invalidation
        run: |
          aws cloudfront create-invalidation \
                --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
                --paths "/${{ env.FE_PROD_PATH }}${{ env.FE_CACHE_PATH }}"
