name: Frontend CD

on:
  # fe/prod 에 브랜치가 푸시될 때
  push:
    branches:
      - fe/prod
      - main

env:
  FE_PROD_PATH: fe-prod

jobs:
  ci:
    uses: ./.github/workflows/frontend-ci.yml

  cd:
    needs: ci
    runs-on: [ self-hosted, Linux, ARM64 ]
    
    # 동일한 워크플로가 실행되었을 시 이전 워크플로를 취소하고 최신 버젼을 실행
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    
    steps:
      - name: Remove previous version app
        working-directory: .
        run: rm -rf frontend/

      - name: Download the built file from CI
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend
        timeout-minutes: 5

      - name: Upload to S3
        run: |
          aws s3 sync frontend s3://techcourse-project-2025/coffee-shout/${{ env.FE_PROD_PATH }}/ --delete

      # 캐시 무효화를 통해서 클라우드 프론트에 최신 버젼으로 노출될 수 있도록 함
      - name: CloudFront invalidation
        run: |
          aws cloudfront create-invalidation \
                --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} \
                --paths "/${{ env.FE_PROD_PATH }}/*"
