name: Frontend CI

on:
  # PR이 열릴 때, 업데이트될 때, 다시 열릴 때
  pull_request:
    branches: [fe/dev, fe/prod]
    paths:
      - "frontend/**"

  # 커밋이 푸시될 때
  push:
    branches: [fe/dev, fe/prod]
    paths:
      - "frontend/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    # frontend 폴더를 기본 작업 디렉토리로 설정
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Run Tests
        run: npm run test:jest
        env:
          CI: true

      - name: Run Build
        run: npm run build
